config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'

  # resources :books, only: [:index, :show, :new, :create, :destroy] do
  #   resources :reviews, only: [:new, :create, :destroy]
  #   resources :authors, only: [:new, :destroy, :create]
  # end

  # resources :authors, only: [:show, :destroy]
  #   resources :books, only: [:destroy]

  # resources :reviews, only: [:index, :destroy]


  # resources :reviews, only: [:destroy]

  #book routes
get '/books', to: 'books#index'
get '/books/:id', to: 'books#show', as: :book
get '/book/new', to: 'books#new', as: :new_book
post '/books', to: 'books#create'
delete '/books/:id', to: 'books#destroy'

#book review routes
get '/books/:book_id/review/new', to: 'reviews#new', as: :new_book_review
post '/books/:book_id/reviews', to: 'reviews#create', as: :book_reviews
delete '/books/:book_id/reviews/:id', to: 'reviews#destroy', as: :book_review

#book author routes
get '/books/:book_id/author/new', to: 'authors#new', as: :new_book_author
post '/books/:book_id/authors', to: 'authors#create', as: :book_authors
delete '/books/:book_id/authors/:id', to: 'authors#destroy', as: :book_author

#author routes
get 'authors/:id', to: 'authors#show'
delete 'authors/:id', to: 'authors#destroy', as: :author

#review_routes
get '/reviews', to: 'reviews#index'
delete 'reviews/:id', to: 'reviews#destroy', as: :review



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    validates_presence_of :name
    has_many :bookauthors, dependent: :destroy
    has_many :books, through: :bookauthors

    before_save { self.name = self.name.titleize }
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true, uniqueness: true, length: { maximum: 75 }
  validates :page_count, presence: true, numericality: { greater_than: 0, only_integer: true }
  validates :pub_year, presence: true, numericality: {greater_than: 1000, less_than: 2030, only_integer: true}

  has_many :reviews, dependent: :destroy
  has_many :bookauthors, dependent: :destroy
  has_many :authors, through: :bookauthors

  before_save { self.title = self.title.titleize }
  before_save {
    if self.thumbnail_url == ""
      self.thumbnail_url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSd3cgsv8lMoNU4g8dDN1hUqKlXAR3DTITUd5rl1tMuYds_wAP6"
    end
  }

  def highest_three_reviews
    reviews.order(:score).last(3).reverse
  end

  def lowest_three_reviews
    reviews.order(:score).first(3)
  end

  def average_review_score
    raw_mean = reviews.average(:score).to_f
    raw_mean.round(2)
  end

  def review_count
    reviews.count
  end

  def coauthors(excluded_author)
    authors.where.not(id: excluded_author.id)
  end

  def self.descending_pages
    Book.order(page_count: :desc)
  end

  def self.ascending_pages
    Book.order(page_count: :asc)
  end

  def self.descending_rating
    Book.joins(:reviews)
        .select('books.*,AVG(reviews.score) AS avg_review')
        .group(:id)
        .order('avg_review DESC, books.title ASC')
    
  end

  def self.ascending_rating
    Book.joins(:reviews)
        .select('books.*,AVG(reviews.score) AS avg_review')
        .group(:id)
        .order('avg_review ASC, books.title ASC')
  end

  def self.descending_reviews
    Book.joins(:reviews)
        .select('books.*,COUNT(reviews) AS review_count')
        .group(:id)
        .order('review_count DESC, books.title ASC')

    # Book.all.sort_by do |book|
    #   book.review_count
    # end.reverse
  end

  def self.ascending_reviews
    Book.joins(:reviews)
        .select('books.*,COUNT(reviews) AS review_count')
        .group(:id)
        .order('review_count ASC, books.title ASC')
  end

  def self.highest_three_scores
    Book.joins(:reviews)
        .select('books.*,AVG(reviews.score) AS avg_review')
        .group(:id)
        .order('avg_review DESC, books.title ASC')
        .limit(3)
  end

  def self.lowest_three_scores
    Book.joins(:reviews)
        .select('books.*,AVG(reviews.score) AS avg_review')
        .group(:id)
        .order('avg_review ASC, books.title ASC')
        .limit(3)
  end
end

app/models/bookauthor.rb
class Bookauthor < ApplicationRecord
    validates_presence_of :author_id
    validates_presence_of :book_id
    belongs_to :book
    belongs_to :author
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :book
    validates_presence_of :heading, :score, :full_review, :username, :book_id

    before_save {self.username = self.username.titleize}

  def self.newest
    order(created_at: :asc)
  end

  def self.oldest
    order(created_at: :desc)
  end

  def self.top_three_reviewers
    review_groups = Review.all.group_by {|review| review.username}
    
    reviewer_count = review_groups.each do |key, value|
      review_groups[key] = value.count 
    end

    sorted_reviewers = reviewer_count.sort_by {|reviewer, count| count}

    sorted_reviewers.reverse[0..2]

  end
end

app/models/welcome.rb
class Welcome < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    def show
        @author = Author.find(params[:id])
        @num_reviews = @author.books.map do |book|
          book.reviews.count
        end
    end

    def destroy
      author = Author.find(params[:id])
      author.books.each do |book|
        book.destroy
      end
      author.destroy
      redirect_to books_path
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @stat_books = Book.all
    @user_reviews = Review.all
    if params[:sort] == "descending_pages"
      @books = Book.all.descending_pages
    elsif params[:sort] == "ascending_pages"
      @books = Book.all.ascending_pages
    elsif params[:sort] == "descending_rating"
      @books = Book.all.descending_rating
    elsif params[:sort] == "ascending_rating"
      @books = Book.all.ascending_rating
    elsif params[:sort] == "descending_reviews"
      @books = Book.all.descending_reviews
    elsif params[:sort] == "ascending_reviews"
      @books = Book.all.ascending_reviews
    else
      @books = Book.all
    end
  end

  def show
   @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if Book.find_by(title: @book.title.titleize) == nil
      if @book.save
        author_params[:authors].split(',').each do |author_param|
          if Author.find_by(name: author_param.strip.titleize)
            @book.authors << Author.find_by(name: author_param.strip.titleize)
          else
          @book.authors.create(name: author_param.strip)
          end
        end
        redirect_to book_path(@book)
      else
      render :new
      end
    else
      redirect_to new_book_path
    end
  end

  def destroy
    Book.destroy(params[:id])
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :pub_year, :page_count, :thumbnail_url)
  end

  def author_params
    params.permit(:authors)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @book = Book.find(params[:book_id])
    @review = Review.new
  end

  def create
    @book = Book.find(params[:book_id])
    @review = @book.reviews.new(review_params)
    @review.save
    redirect_to book_path(@book)
  end

  def index
    @user = params[:arg]
    if params[:sort] == "newest"
      @reviews = Review.where(username: @user).newest
    elsif
      params[:sort] == "oldest"
      @reviews = Review.where(username: @user).oldest
    else
        @reviews = Review.where(username: @user)
    end
  end

  def destroy
    review = Review.find(params[:id])
    user = review.username
    review.destroy
    redirect_to reviews_path(arg: user)
  end

private
  def review_params
    params.require(:review).permit(:heading, :score, :full_review, :username)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController 
    def index   
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/show.html.erb
<h1><%= @author.name %></h1>
<h2>Books:</h2>

<ul id='author-books-list'>
    <% @author.books.each do |book| %>
        <ul id="<%= book.id %>">
          <li><%= link_to book.title, book_path(book) %></li>
          <li><%= book.page_count %></li>
          <li><%= book.pub_year %></li>
          <% if @num_reviews.include?(0) == false %>
            <li><%= book.highest_three_reviews[0].username %></li>
            <li><%= book.highest_three_reviews[0].score %>/5</li>
            <li><%= book.highest_three_reviews[0].heading %></li>
          <% end %>
          <ul><% book.coauthors(@author).each do |author| %>
              <li><%= link_to author.name, author_path(author) %></li>
              <% end %>
          </ul>
        <br>
        <li><img src="<%= book.thumbnail_url %>" alt="Book Thumbnail"></li>
        <% if @num_reviews.include?(0) == false %>
          <li><%= link_to "#{book.highest_three_reviews[0].username}", reviews_path(arg: book.highest_three_reviews[0].username) %></li>
          <li><%= book.highest_three_reviews[0].score %>/5</li>
          <li><%= book.highest_three_reviews[0].heading %></li>
        <% end %>
        </ul>
    <% end %>
    <%= link_to "Delete Author", author_path(@author), method: :delete %>
</ul>

app/views/books/index.html.erb
<h1>All Books</h1>
<%= link_to "Add book", new_book_path %>

<div id="stats-box">
  <h4>Highest Rated Books</h4>
  <div id="top-rated">
      <% @stat_books.highest_three_scores.each do |book| %>
      <ul>
        <li>Title: <%= link_to book.title, book_path(book) %></li>
        <li>Rating: <%= book.average_review_score %></li>
      </ul>
        <br>
      <% end %>
  </div>
  <br>
  <h4>Lowest Rated Books</h4>
  <div id="lowest-rated">
      <% @stat_books.lowest_three_scores.each do |book| %>
        <ul>
          <li>Title: <%= link_to book.title, book_path(book) %></li>
          <li>Rating: <%= book.average_review_score %></li>
        </ul>
        <br>
      <% end %>
  </div>
  <h4>Most Active Users</h4>
  <div id="user-review-stats">
    <% @user_reviews.top_three_reviewers.each do |review_pair| %>
      <ul>
        <li>User: <%= link_to "#{review_pair[0]}", reviews_path(arg: review_pair[0]) %></li>
        <li>Review Count: <%= review_pair[1] %></li>
      </ul>
      <br>
    <% end %>
  </div>
  <br>
</div>

<ul class='sort-links'>
    <%= link_to 'Most Pages', books_path(sort: 'descending_pages') %>
    <%= link_to 'Least Pages', books_path(sort: 'ascending_pages') %>
    <%= link_to 'Highest Ratings', books_path(sort: 'descending_rating') %>
    <%= link_to 'Lowest Ratings', books_path(sort: 'ascending_rating') %>
    <%= link_to 'Most Reviews', books_path(sort: 'descending_reviews') %>
    <%= link_to 'Least Reviews', books_path(sort: 'ascending_reviews') %>
</ul>

<div id="book-list">
<% @books.each do |book| %>
  <div id="book-card">
    <div id="<%=book.id%>">
      <div class="book-info">
        <h2>Title: <%= link_to book.title, book_path(book) %></h2>
        <h5>Average score: <%= book.average_review_score %></h5>
        <h5>Total reviews: <%= book.review_count %></h5>
      
        <h2>Author(s):</h2>
          <% book.authors.each do |author|%>
            <ul>
            <li><%= link_to "#{author.name}", author_path(author) %></li>
            </ul>
          <% end %>
        <p>Pages: <%= book.page_count %></p>
        <p>Publication Year: <%= book.pub_year %></p>
      </div>
        <img height="200" width="150" src="<%= book.thumbnail_url %>" alt="Book Thumbnail">
    </div>
  </div>
<% end %>
</div>

app/views/books/new.html.erb
<% if @book.errors.any? %>
  <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
<% end %>
<%= form_for @book do |f| %>
  <div id="title">  <%= f.label :title %>
  <%= f.text_field :title %></div>
  <div id="pub-year"><%= f.label :pub_year %>
  <%= f.number_field :pub_year, in: 1000..Time.now.year %></div>
  <div id="page-count"><%= f.label :page_count %>
  <%= f.number_field :page_count %></div>
  <div id="thumbnail-url"><%= f.label :thumbnail_url %>
  <%= f.text_field :thumbnail_url %></div>
  <div id="authors"><%= label_tag :authors %>
  <%= text_field_tag :authors %></div>
  <%= f.submit %>
<% end %>

app/views/books/show.html.erb
<h1>Title: <%= link_to @book.title, book_path(@book) %></h1>
<h3>Average Review Score: <%= @book.average_review_score %></h3>
<h3>Total Reviews: <%= @book.review_count %></h3>

  <p>
    <ul><li>Page Count: <%= @book.page_count %></li>
      <li>Publication Year: <%= @book.pub_year %></li>
      <ul>Author(s):<% @book.authors.each do |author|%>
        <li><%= link_to "#{author.name}", author_path(author)%></li>
        <% end %></ul>
      <li><img src="<%= @book.thumbnail_url %>" alt="Book Thumbnail"></li>
      <br>
      <li>Reviews:<% @book.reviews.each do |review|%>
        <section id=<%= "review-#{review.id}" %>>
          <ul><li>Review title: <%= review.heading %></li>
            <li>Reviewed by: <%= link_to "#{review.username}", reviews_path(arg: review.username) %></li>
            <li>Rating: <%= review.score %>/5</li>
            <li><%= review.full_review %></li></ul>
            <br>
        </section>
        <% end %></li>
        <br>
        <ul id="review-stats">Review Stats:
          <ul id="highest">
            <li>Highest 3 Reviews: <% @book.highest_three_reviews.each do |review| %>
              <ul>
                <li><%= review.heading %></li>
                <li><%= review.score %>/5</li>
                <li><%= link_to "#{review.username}", reviews_path(arg: review.username) %></li>
                <br>
              </ul>
            <% end %></li>
          </ul>
          <ul id="lowest">
            <li>Lowest 3 Reviews: <% @book.lowest_three_reviews.each do |review| %>
              <ul>
                <li><%= review.heading %></li>
                <li><%= review.score %>/5</li>
                <li><%= link_to "#{review.username}", reviews_path(arg: review.username) %></li>
                <br>
              </ul>
            <% end %></li>
          </ul>
        </ul>
      </ul>
  </p>
<%= link_to "<< Back to Books Home", books_path %>

<%= link_to "Add Review", new_book_review_path(@book) %>

<%= link_to "Delete Book", book_path(@book), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookClub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <header>
    <div class="topnav" width="1200" height="600">
      <%= link_to 'Home', root_path %>
      <%= link_to 'Books', books_path %>
     </div>
  </header>


  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/index.html.erb
<h1> <%= @user %></h1>
<section id="sort-reviews">
  <%= link_to 'Newest Reviews', reviews_path(arg: @user, sort: "newest")%>
  <%= link_to 'Oldest Reviews', reviews_path(arg: @user, sort: "oldest")%>
</section>

<% @reviews.each do |r| %>
  <section class="review" id=<%="review-#{r.id}"%>>
    <p><%= link_to r.book.title, book_path(r.book) %></p>
    <p><%= r.heading %></p>
    <p><%= r.score %></p>
    <p><%= r.full_review %></p>
    <p><%= r.created_at.to_date.to_s %></p>
    <%= image_tag "#{r.book.thumbnail_url}" %></p>
    <!-- <p><%= link_to "Delete Review", book_review_path(book_id: r.book.id, id: r.id), method: :delete %></p> -->
    <p><%= link_to "Delete Review", review_path(r.id), method: :delete %></p>

  </section>
<% end %>

app/views/reviews/new.html.erb
<%= form_for [@book, @review] do |f| %>
  <p>
    <%= f.label :heading %><br/>
    <%= f.text_field :heading %>
  </p>
  <p>
    <%= f.label :score %><br/>
    <%= f.number_field :score, in: 1..5 %>

  </p>
  <p>
    <%= f.label :full_review %><br/>
    <%= f.text_field :full_review %>
  </p>
  <p>
    <%= f.label :username %><br/>
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.submit  %>
  </p>
<% end %>

app/views/welcome/index.html.erb
<div id="welcome-box">
    <div id="welcome-msg">
        <h1>Welcome to Book Club!</h1>
    </div>
    <div id="welcome-books">
            <img src="https://cdn-image.travelandleisure.com/sites/default/files/styles/1600x1000/public/201407-w-most-beautiful-libraries-in-the-world-klementinum-prague.jpg?itok=iEn3LTLq" width="1200" height="750">
    </div>    
</div>